# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmGFpOKx7hw_AgCVAlZReVHL22TGaLMB
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

#loading
file_path = '/content/drive/MyDrive/Colab_Notebooks/CEEW - Smart meter data Bareilly 2020.csv'
data = pd.read_csv(file_path)
print(data.head())

# Convert timestamp to datetime
data['x_Timestamp'] = pd.to_datetime(data['x_Timestamp'])

#model creation
features = ['z_Avg Voltage (Volt)', 'z_Avg Current (Amp)', 'y_Freq (Hz)']
target = 't_kWh'

X = data[features]
y = data[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Ridge()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

plt.scatter(y_test, y_pred)
plt.xlabel('Actual Consumption (t_kWh)')
plt.ylabel('Predicted Consumption (t_kWh)')
plt.title('Actual vs Predicted Consumption')
plt.show()


coefficients = pd.DataFrame(model.coef_, features, columns=['Coefficient'])
print(coefficients)